#Uncomment lines 11, 12 to get access to the database for testing
version: "3.1"
services:
  postgres:
    image: postgres:13.1-alpine
    restart: always
    volumes:
        - ./db_config:/docker-entrypoint-initdb.d
        - ./.db_data:/var/lib/postgresql/data
        - ./db_populate:/populate

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clup
    networks:
      internal:

  nginx:
    image: nginx:1.18
    container_name: clup-nginx
    restart: always
    depends_on: 
      - clup-server
    ports:
      - "80:80"
      - "443:443"
    networks: 
      internal:
    volumes:
      - ./data/nginx_conf:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
  clup-server:
    build: ./clup-server
    restart: always
    environment:
      - JWT_SECRET_KEY
    depends_on: 
      - postgres
    networks:
      internal:

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

      
    
networks:
  internal:
