#Uncomment lines 11, 12 to get access to the database for testing
version: "3.1"
services:
  postgres:
    image: postgres:13.1-alpine
    restart: always
    volumes:
        - ./db_config:/docker-entrypoint-initdb.d
        - ./.db_data:/var/lib/postgresql/data
        - ./db_populate:/populate
    ports:
        - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clup
    networks:
      internal:

  pgadmin:
    image: dpage/pgadmin4:4.29
    depends_on: 
      - postgres
    ports:
      - "80:80"
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@clup.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      internal:
      
    
networks:
  internal: