#Uncomment lines 11, 12 to get access to the database for testing
version: "3.1"
services:
  postgres:
    image: postgres:13.1-alpine
    restart: always
    volumes:
        - ./db_config:/docker-entrypoint-initdb.d
        - ./.db_data:/var/lib/postgresql/data
        - ./db_populate:/populate

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clup
    networks:
      internal:

  nginx:
    image: nginx:1.18
    container_name: clup-nginx
    restart: always
    depends_on: 
      - clup-server
    ports:
      - "80:80"
    networks: 
      internal:
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
  
  clup-server:
    build: ./clup-server
    restart: always
    environment:
      - JWT_SECRET_KEY
    depends_on: 
      - postgres
    networks:
      internal:
      
    
networks:
  internal:
